# Generated by Django 4.0.5 on 2022-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_thirname', models.CharField(max_length=40)),
                ('cart_number', models.IntegerField(null=True)),
                ('cart_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
