# Generated by Django 4.0.5 on 2022-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_age',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
