# Generated by Django 4.0.5 on 2022-07-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0002_client_client_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_gender',
            field=models.CharField(default='NONE', max_length=40),
        ),
    ]
