# Generated by Django 4.0.5 on 2022-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0003_client_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='carrancy',
            field=models.CharField(choices=[('USD', 'dollar'), ('EUR', 'euro'), ('UKR', 'grivnia')], default='USD', max_length=3),
        ),
    ]
