# Generated by Django 4.0.5 on 2022-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0004_client_carrancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(default='monobank', max_length=100),
        ),
    ]
