# Generated by Django 4.0.5 on 2022-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0005_client_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_email',
            field=models.EmailField(default='bank@gmail.com', max_length=254),
        ),
    ]
