# Generated by Django 4.0.5 on 2022-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0006_client_bank_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_name',
        ),
    ]
