# Generated by Django 4.0.5 on 2022-08-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0009_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
